name: Run CI for API

on:
  pull_request:
    paths:
      - "example/RResult.Api/**"
      - "example/RResult.Api.Test/**"
  schedule:
    - cron: "00 11 * * *"

defaults:
  run:
    working-directory: example/RResult.Api

jobs:
  dotnet-ci:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        dotnet: ["8.0.x"]
    name: Dotnet ${{ matrix.dotnet }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Format
        run: dotnet format --verify-no-changes --verbosity diagnostic ./RResult.Api.sln
