name: Release nunuget package

on:
  release:
    types: [published]

defaults:
  run:
    working-directory: src

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        dotnet: ["8.0.x"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build with dotnet
        run: dotnet build --no-restore
      - name: Release Package
        run: |
          dotnet nuget push RResult/bin/Release/RResult.${{ github.event.release.tag_name }}.nupkg --api-key ${{secrets.NUGET_APIKEY}} --source https://api.nuget.org/v3/index.json
  
